spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  #DB mysql로 변경
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      # 테스트 완료 시 create로 변경
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true -> System.out에 하이버네이트 실행 SQL을 남김
        #        로거를 통해 하이버네이트 실행 SQL을 남기는 옵션이 있으므로 필요 X
        format_sql: true

#서버 포트 설정
server:
  port: 4000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

# HS512 알고리즘의 시크릿키 : 512비트 (64바이트) 이상
# https://passwords-generator.org/kr/
# 사이트에서 길이:64 로 생성함.
jwt:
  secret: ${SPRING_JWT_SECRET_KEY}

# 파일 업로드
file:
  path: ${UPLOAD_FILE_PATH}
  url: ${UPLOAD_FILE_URL}