spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:h2:tcp://localhost/~/snaphubDB
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true -> System.out에 하이버네이트 실행 SQL을 남김
        #        로거를 통해 하이버네이트 실행 SQL을 남기는 옵션이 있으므로 필요 X
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

# HS512 알고리즘의 시크릿키 : 512비트 (64바이트) 이상
# https://passwords-generator.org/kr/
# 사이트에서 길이:64 로 생성함.
jwt:
  secret: "|+<T%0h;[G97|I$5Lr?h]}`8rUX.7;0gw@bF<R/|\"'-U0n:_6j={'.T'GHs~<AxU9"